# Form implementation generated from reading ui file 'ui/sum_div.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SumDivWindow(object):
    def setupUi(self, SumDivWindow):
        SumDivWindow.setObjectName("SumDivWindow")
        SumDivWindow.resize(359, 171)
        self.gridLayout = QtWidgets.QGridLayout(SumDivWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(SumDivWindow)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(SumDivWindow)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.line_firstNum = QtWidgets.QLineEdit(SumDivWindow)
        self.line_firstNum.setText("")
        self.line_firstNum.setObjectName("line_firstNum")
        self.gridLayout.addWidget(self.line_firstNum, 1, 0, 1, 1)
        self.line_secondNum = QtWidgets.QLineEdit(SumDivWindow)
        self.line_secondNum.setText("")
        self.line_secondNum.setObjectName("line_secondNum")
        self.gridLayout.addWidget(self.line_secondNum, 1, 1, 1, 1)
        self.rad_sum = QtWidgets.QRadioButton(SumDivWindow)
        self.rad_sum.setChecked(True)
        self.rad_sum.setObjectName("rad_sum")
        self.gridLayout.addWidget(self.rad_sum, 2, 0, 1, 1)
        self.rad_div = QtWidgets.QRadioButton(SumDivWindow)
        self.rad_div.setObjectName("rad_div")
        self.gridLayout.addWidget(self.rad_div, 2, 1, 1, 1)
        self.btn_calc = QtWidgets.QPushButton(SumDivWindow)
        self.btn_calc.setObjectName("btn_calc")
        self.gridLayout.addWidget(self.btn_calc, 3, 0, 1, 2)
        self.label = QtWidgets.QLabel(SumDivWindow)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.label_result = QtWidgets.QLabel(SumDivWindow)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_result.setFont(font)
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.gridLayout.addWidget(self.label_result, 4, 1, 1, 1)

        self.retranslateUi(SumDivWindow)
        QtCore.QMetaObject.connectSlotsByName(SumDivWindow)

    def retranslateUi(self, SumDivWindow):
        _translate = QtCore.QCoreApplication.translate
        SumDivWindow.setWindowTitle(_translate("SumDivWindow", "Сумма и деление двух чисел"))
        self.label_2.setText(_translate("SumDivWindow", "Первое число:"))
        self.label_3.setText(_translate("SumDivWindow", "Второе число:"))
        self.rad_sum.setText(_translate("SumDivWindow", "Сложение"))
        self.rad_div.setText(_translate("SumDivWindow", "Деление"))
        self.btn_calc.setText(_translate("SumDivWindow", "Расчитать"))
        self.label.setText(_translate("SumDivWindow", "Результат:"))
